on:
  push:

jobs:
  test-job:
    runs-on: ubuntu:latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install packages
        run: npm install

      - name: Test the code
        run: npm test
